# Generated by Django 3.0.3 on 2020-06-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(choices=[('H', 'Hybrid'), ('E', 'Electric'), ('D', 'Diesel'), ('P', 'Petrol')], default='H', max_length=1)),
                ('displacement', models.PositiveIntegerField(default=0)),
                ('power', models.PositiveIntegerField(default=0)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='data_input.Manufacturer')),
            ],
        ),
    ]
